apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  stripPrefix:
    prefixes:
      - ${prometheus_path_prefix}
      - ${grafana_path_prefix}
