/*
 * API Artisashop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtisashopApi.Api;
using ArtisashopApi.Model;
using ArtisashopApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtisashopApi.Test.Model
{
    /// <summary>
    ///  Class for testing Contact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Contact
        //private Contact instance;

        public ContactTests()
        {
            // TODO uncomment below to create an instance of Contact
            //instance = new Contact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Contact
        /// </summary>
        [Fact]
        public void ContactInstanceTest()
        {
            // TODO uncomment below to test "IsType" Contact
            //Assert.IsType<Contact>(instance);
        }


        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Receiver'
        /// </summary>
        [Fact]
        public void ReceiverTest()
        {
            // TODO unit test for the property 'Receiver'
        }

    }

}
