/*
 * API Artisashop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArtisashopApi.Api;
using ArtisashopApi.Model;
using ArtisashopApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArtisashopApi.Test.Model
{
    /// <summary>
    ///  Class for testing PaypalBill
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaypalBillTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaypalBill
        //private PaypalBill instance;

        public PaypalBillTests()
        {
            // TODO uncomment below to create an instance of PaypalBill
            //instance = new PaypalBill();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaypalBill
        /// </summary>
        [Fact]
        public void PaypalBillInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaypalBill
            //Assert.IsType<PaypalBill>(instance);
        }


        /// <summary>
        /// Test the property 'PurchaseUnits'
        /// </summary>
        [Fact]
        public void PurchaseUnitsTest()
        {
            // TODO unit test for the property 'PurchaseUnits'
        }

    }

}
