FROM node:18 as build
ENV NODE_ENV development
RUN ["corepack", "enable"]
RUN ["yarn", "set", "version", "stable"]
WORKDIR /usr/src/app
COPY package.json yarn.lock .yarn .yarnrc.yml ./
RUN yarn install
COPY . ./
CMD ["yarn", "start"]
