FROM node:18 as build
RUN ["yarn", "--verions"]
RUN ["corepack", "enable"]
RUN ["yarn", "set", "version", "stable"]
WORKDIR /usr/src/app
COPY package.json yarn.lock .yarn .yarnrc.yml ./
RUN yarn install
RUN ["ls"]
COPY . ./
CMD ["yarn", "start"]
