version: "3.8"
services:
  # backend:
  #   env_file:
  #     - development.env
  #   restart: always
  #   build:
  #     context: ./Backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 7095:80
  #   volumes:
  #     - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
  #   networks:
  #     - db-tier
  #     - mail-tier
  #   depends_on:
  #     - postgres

  # frontend:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - development.env

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dbsrcipts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    networks:
      - db-tier

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - db-tier

  smtp-server:
    image: namshi/smtp:latest
    restart: unless-stopped
    networks:
      - mail-tier
    environment:
      - SMARTHOST_USER=artisashop
      - SMARTHOST_PASSWORD=artisashop2021=)
    ports:
      - 25:25

volumes:
  db-data:

networks:
  db-tier:
    driver: bridge
  mail-tier:
    driver: bridge