version: "3.9"
services:
  backend:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - PARSE_ARTISASHOP_MASTER_KEY=${PARSE_ARTISASHOP_MASTER_KEY}
      - PARSE_ARTISASHOP_RESTAPI_KEY=${PARSE_ARTISASHOP_RESTAPI_KEY}
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    networks:
      - parse-tier
      - db-tier
      - mail-tier
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisaback.rule=Host(`${ARTISASHOP_API_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisaback.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisaback.middlewares=${COMPOSE_PROJECT_NAME}-redirect-shop"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-shop.redirectregex.regex=(http(s*)://)?${ARTISASHOP_API_HOST}/?(.*)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-shop.redirectregex.replacement=https://${ARTISASHOP_API_HOST}/$${3}"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-core.rule=Host(`${ARTISASHOP_API_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-core.entrypoints=websecure"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-core.loadbalancer.server.port=80"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisafront.rule=Host(`${ARTISASHOP_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisafront.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisafront.middlewares=${COMPOSE_PROJECT_NAME}-redirect-shop"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-shop.redirectregex.regex=(http(s*)://)?${ARTISASHOP_HOST}/?(.*)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-shop.redirectregex.replacement=https://${ARTISASHOP_HOST}/$${3}"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-core.rule=Host(`${ARTISASHOP_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-core.entrypoints=websecure"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-core.loadbalancer.server.port=80"

  smtp-server:
    image: namshi/smtp:latest
    restart: unless-stopped
    networks:
      - mail-tier
    environment:
      - SMARTHOST_USER=artisashop
      - SMARTHOST_PASSWORD=artisashop2021=)
    ports:
      - 25:25

volumes:
  db-data:

networks:
  db-tier:
    driver: bridge
  parse-tier:
    driver: bridge
  mail-tier:
    driver: bridge