/*
 * API Artisashop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using ArtisashopApi.Client;
using ArtisashopApi.Model;

namespace ArtisashopApi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAdminUserRoleApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;StringIdentityUserRole&gt;</returns>
        List<StringIdentityUserRole> ApiAdminUserRoleGet(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;StringIdentityUserRole&gt;</returns>
        ApiResponse<List<StringIdentityUserRole>> ApiAdminUserRoleGetWithHttpInfo(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        StringIdentityUserRole ApiAdminUserRoleIdDelete(int id, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        ApiResponse<StringIdentityUserRole> ApiAdminUserRoleIdDeleteWithHttpInfo(int id, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        StringIdentityUserRole ApiAdminUserRoleIdGet(int id, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        ApiResponse<StringIdentityUserRole> ApiAdminUserRoleIdGetWithHttpInfo(int id, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        StringIdentityUserRole ApiAdminUserRoleIdPut(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        ApiResponse<StringIdentityUserRole> ApiAdminUserRoleIdPutWithHttpInfo(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        StringIdentityUserRole ApiAdminUserRolePost(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        ApiResponse<StringIdentityUserRole> ApiAdminUserRolePostWithHttpInfo(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAdminUserRoleApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;StringIdentityUserRole&gt;</returns>
        System.Threading.Tasks.Task<List<StringIdentityUserRole>> ApiAdminUserRoleGetAsync(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;StringIdentityUserRole&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<StringIdentityUserRole>>> ApiAdminUserRoleGetWithHttpInfoAsync(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRoleIdDeleteAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        System.Threading.Tasks.Task<ApiResponse<StringIdentityUserRole>> ApiAdminUserRoleIdDeleteWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRoleIdGetAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        System.Threading.Tasks.Task<ApiResponse<StringIdentityUserRole>> ApiAdminUserRoleIdGetWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRoleIdPutAsync(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        System.Threading.Tasks.Task<ApiResponse<StringIdentityUserRole>> ApiAdminUserRoleIdPutWithHttpInfoAsync(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRolePostAsync(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        System.Threading.Tasks.Task<ApiResponse<StringIdentityUserRole>> ApiAdminUserRolePostWithHttpInfoAsync(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAdminUserRoleApi : IAdminUserRoleApiSync, IAdminUserRoleApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AdminUserRoleApi : IAdminUserRoleApi
    {
        private ArtisashopApi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminUserRoleApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AdminUserRoleApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminUserRoleApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AdminUserRoleApi(string basePath)
        {
            this.Configuration = ArtisashopApi.Client.Configuration.MergeConfigurations(
                ArtisashopApi.Client.GlobalConfiguration.Instance,
                new ArtisashopApi.Client.Configuration { BasePath = basePath }
            );
            this.Client = new ArtisashopApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ArtisashopApi.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = ArtisashopApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminUserRoleApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AdminUserRoleApi(ArtisashopApi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = ArtisashopApi.Client.Configuration.MergeConfigurations(
                ArtisashopApi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new ArtisashopApi.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ArtisashopApi.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = ArtisashopApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminUserRoleApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AdminUserRoleApi(ArtisashopApi.Client.ISynchronousClient client, ArtisashopApi.Client.IAsynchronousClient asyncClient, ArtisashopApi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = ArtisashopApi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public ArtisashopApi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ArtisashopApi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ArtisashopApi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ArtisashopApi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;StringIdentityUserRole&gt;</returns>
        public List<StringIdentityUserRole> ApiAdminUserRoleGet(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0)
        {
            ArtisashopApi.Client.ApiResponse<List<StringIdentityUserRole>> localVarResponse = ApiAdminUserRoleGetWithHttpInfo(filter, range, sort);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;StringIdentityUserRole&gt;</returns>
        public ArtisashopApi.Client.ApiResponse<List<StringIdentityUserRole>> ApiAdminUserRoleGetWithHttpInfo(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0)
        {
            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtisashopApi.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (range != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtisashopApi.Client.ClientUtils.ParameterToMultiMap("", "range", range));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtisashopApi.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<StringIdentityUserRole>>("/api/admin/userRole", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;StringIdentityUserRole&gt;</returns>
        public async System.Threading.Tasks.Task<List<StringIdentityUserRole>> ApiAdminUserRoleGetAsync(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArtisashopApi.Client.ApiResponse<List<StringIdentityUserRole>> localVarResponse = await ApiAdminUserRoleGetWithHttpInfoAsync(filter, range, sort, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="range"> (optional, default to &quot;&quot;)</param>
        /// <param name="sort"> (optional, default to &quot;&quot;)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;StringIdentityUserRole&gt;)</returns>
        public async System.Threading.Tasks.Task<ArtisashopApi.Client.ApiResponse<List<StringIdentityUserRole>>> ApiAdminUserRoleGetWithHttpInfoAsync(string? filter = default(string?), string? range = default(string?), string? sort = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtisashopApi.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (range != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtisashopApi.Client.ClientUtils.ParameterToMultiMap("", "range", range));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(ArtisashopApi.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<StringIdentityUserRole>>("/api/admin/userRole", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        public StringIdentityUserRole ApiAdminUserRoleIdDelete(int id, int operationIndex = 0)
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = ApiAdminUserRoleIdDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        public ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> ApiAdminUserRoleIdDeleteWithHttpInfo(int id, int operationIndex = 0)
        {
            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", ArtisashopApi.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<StringIdentityUserRole>("/api/admin/userRole/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        public async System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRoleIdDeleteAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = await ApiAdminUserRoleIdDeleteWithHttpInfoAsync(id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        public async System.Threading.Tasks.Task<ArtisashopApi.Client.ApiResponse<StringIdentityUserRole>> ApiAdminUserRoleIdDeleteWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", ArtisashopApi.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleIdDelete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<StringIdentityUserRole>("/api/admin/userRole/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleIdDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        public StringIdentityUserRole ApiAdminUserRoleIdGet(int id, int operationIndex = 0)
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = ApiAdminUserRoleIdGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        public ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> ApiAdminUserRoleIdGetWithHttpInfo(int id, int operationIndex = 0)
        {
            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", ArtisashopApi.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleIdGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<StringIdentityUserRole>("/api/admin/userRole/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleIdGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        public async System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRoleIdGetAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = await ApiAdminUserRoleIdGetWithHttpInfoAsync(id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        public async System.Threading.Tasks.Task<ArtisashopApi.Client.ApiResponse<StringIdentityUserRole>> ApiAdminUserRoleIdGetWithHttpInfoAsync(int id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", ArtisashopApi.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleIdGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<StringIdentityUserRole>("/api/admin/userRole/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleIdGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        public StringIdentityUserRole ApiAdminUserRoleIdPut(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0)
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = ApiAdminUserRoleIdPutWithHttpInfo(id, stringIdentityUserRole);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        public ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> ApiAdminUserRoleIdPutWithHttpInfo(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0)
        {
            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", ArtisashopApi.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = stringIdentityUserRole;

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleIdPut";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<StringIdentityUserRole>("/api/admin/userRole/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleIdPut", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        public async System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRoleIdPutAsync(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = await ApiAdminUserRoleIdPutWithHttpInfoAsync(id, stringIdentityUserRole, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        public async System.Threading.Tasks.Task<ArtisashopApi.Client.ApiResponse<StringIdentityUserRole>> ApiAdminUserRoleIdPutWithHttpInfoAsync(int id, StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", ArtisashopApi.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = stringIdentityUserRole;

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRoleIdPut";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<StringIdentityUserRole>("/api/admin/userRole/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRoleIdPut", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>StringIdentityUserRole</returns>
        public StringIdentityUserRole ApiAdminUserRolePost(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0)
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = ApiAdminUserRolePostWithHttpInfo(stringIdentityUserRole);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of StringIdentityUserRole</returns>
        public ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> ApiAdminUserRolePostWithHttpInfo(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0)
        {
            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = stringIdentityUserRole;

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRolePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<StringIdentityUserRole>("/api/admin/userRole", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRolePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StringIdentityUserRole</returns>
        public async System.Threading.Tasks.Task<StringIdentityUserRole> ApiAdminUserRolePostAsync(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ArtisashopApi.Client.ApiResponse<StringIdentityUserRole> localVarResponse = await ApiAdminUserRolePostWithHttpInfoAsync(stringIdentityUserRole, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ArtisashopApi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stringIdentityUserRole"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StringIdentityUserRole)</returns>
        public async System.Threading.Tasks.Task<ArtisashopApi.Client.ApiResponse<StringIdentityUserRole>> ApiAdminUserRolePostWithHttpInfoAsync(StringIdentityUserRole? stringIdentityUserRole = default(StringIdentityUserRole?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            ArtisashopApi.Client.RequestOptions localVarRequestOptions = new ArtisashopApi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = ArtisashopApi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ArtisashopApi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = stringIdentityUserRole;

            localVarRequestOptions.Operation = "AdminUserRoleApi.ApiAdminUserRolePost";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<StringIdentityUserRole>("/api/admin/userRole", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiAdminUserRolePost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
