/*
 * API Recherche d’entreprises
 *
 * # Bienvenue sur la documentation interactive d'API Recherche d’entreprises ! L’API Recherche d’entreprises permet à tout le monde de rechercher et de trouver  une entreprise française par sa dénomination, ou son adresse. ## Données accessibles dans l'API L’API étant totalement ouverte d'accès, elle comporte des limitations. Ainsi ne sont pas accessibles dans l'API : - les prédécesseurs et successeurs d'un établissement - les entreprises non-diffusibles - les entreprises qui se sont vues refuser leurs immatriculation au RCS  **Attention :** cette API ne permet pas d'accèder aux données complètes de  la  base Sirene, mais uniquement de rechercher une entreprise, par sa dénomination ou son adresse. Pour savoir comment obtenir les données complètes, consultez [notre fiche explicative.](https://api.gouv.fr/guides/quelle-api-sirene)  ## Commencer à utiliser l'API L'API est accessible à partir de cette adresse : [https://recherche-entreprises.api.gouv.fr](https://recherche-entreprises.api.gouv.fr)  **Attention :** Vous devez rajouter votre requête sur l’adresse. ## Limite des requêtes    Le serveur accepte un maximum de 7 requêtes par seconde. Au delà, un code 429 est renvoyé indiquant que la volumétrie d'appels a été dépassée.     ## Monitoring de l'API Une supervision du service en temps réel est disponible à cette adresse : [https://stats.uptimerobot.com/kXzwzfk7BE](https://stats.uptimerobot.com/kXzwzfk7BE) 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: recherche-entreprises@api.gouv.fr
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RechercheEntreprisesApi.Api;
using RechercheEntreprisesApi.Model;
using RechercheEntreprisesApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RechercheEntreprisesApi.Test.Model
{
    /// <summary>
    ///  Class for testing SearchGet200ResponseResultsInnerDirigeantsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchGet200ResponseResultsInnerDirigeantsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchGet200ResponseResultsInnerDirigeantsInner
        //private SearchGet200ResponseResultsInnerDirigeantsInner instance;

        public SearchGet200ResponseResultsInnerDirigeantsInnerTests()
        {
            // TODO uncomment below to create an instance of SearchGet200ResponseResultsInnerDirigeantsInner
            //instance = new SearchGet200ResponseResultsInnerDirigeantsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchGet200ResponseResultsInnerDirigeantsInner
        /// </summary>
        [Fact]
        public void SearchGet200ResponseResultsInnerDirigeantsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchGet200ResponseResultsInnerDirigeantsInner
            //Assert.IsType<SearchGet200ResponseResultsInnerDirigeantsInner>(instance);
        }


        /// <summary>
        /// Test the property 'Nom'
        /// </summary>
        [Fact]
        public void NomTest()
        {
            // TODO unit test for the property 'Nom'
        }
        /// <summary>
        /// Test the property 'Prenoms'
        /// </summary>
        [Fact]
        public void PrenomsTest()
        {
            // TODO unit test for the property 'Prenoms'
        }
        /// <summary>
        /// Test the property 'AnneeDeNaissance'
        /// </summary>
        [Fact]
        public void AnneeDeNaissanceTest()
        {
            // TODO unit test for the property 'AnneeDeNaissance'
        }
        /// <summary>
        /// Test the property 'Qualite'
        /// </summary>
        [Fact]
        public void QualiteTest()
        {
            // TODO unit test for the property 'Qualite'
        }
        /// <summary>
        /// Test the property 'Siren'
        /// </summary>
        [Fact]
        public void SirenTest()
        {
            // TODO unit test for the property 'Siren'
        }
        /// <summary>
        /// Test the property 'Denomination'
        /// </summary>
        [Fact]
        public void DenominationTest()
        {
            // TODO unit test for the property 'Denomination'
        }
        /// <summary>
        /// Test the property 'Sigle'
        /// </summary>
        [Fact]
        public void SigleTest()
        {
            // TODO unit test for the property 'Sigle'
        }

    }

}
