/*
 * API Artisashop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ArtisashopApi.Client.OpenAPIDateConverter;

namespace ArtisashopApi.Model
{
    /// <summary>
    /// OrderList
    /// </summary>
    [DataContract(Name = "OrderList")]
    public partial class OrderList : IEquatable<OrderList>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderList" /> class.
        /// </summary>
        /// <param name="item">item.</param>
        /// <param name="possibleState">possibleState.</param>
        public OrderList(Basket item = default(Basket), List<State> possibleState = default(List<State>))
        {
            this.Item = item;
            this.PossibleState = possibleState;
        }

        /// <summary>
        /// Gets or Sets Item
        /// </summary>
        [DataMember(Name = "item", EmitDefaultValue = false)]
        public Basket Item { get; set; }

        /// <summary>
        /// Gets or Sets PossibleState
        /// </summary>
        [DataMember(Name = "possibleState", EmitDefaultValue = true)]
        public List<State> PossibleState { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderList {\n");
            sb.Append("  Item: ").Append(Item).Append("\n");
            sb.Append("  PossibleState: ").Append(PossibleState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrderList);
        }

        /// <summary>
        /// Returns true if OrderList instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderList to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderList input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Item == input.Item ||
                    (this.Item != null &&
                    this.Item.Equals(input.Item))
                ) && 
                (
                    this.PossibleState == input.PossibleState ||
                    this.PossibleState != null &&
                    input.PossibleState != null &&
                    this.PossibleState.SequenceEqual(input.PossibleState)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Item != null)
                {
                    hashCode = (hashCode * 59) + this.Item.GetHashCode();
                }
                if (this.PossibleState != null)
                {
                    hashCode = (hashCode * 59) + this.PossibleState.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
