/*
 * API Sirene
 *
 * <p><span style=\"color:red;\"> <b></b></p><br></span><span style=\"color:blue;\"> <b>Les tranches d’effectifs et les catégories d’entreprises du millésime 2020 sont désormais disponibles</b></span> <br><br><span style=\"color:blue;\"><i>La documentation des services est désormais au format html (Cf. Onglet Documentation)</i></span></p> <p><h4 class=\"add-margin-top-5x\"><b>Les données du répertoire Sirene depuis 1973</b></h4><p>API Sirene donne accès aux informations concernant les entreprises et les établissements enregistrés au répertoire interadministratif Sirene depuis sa création en 1973, y compris les unités fermées.</p> <p>La recherche peut être unitaire, multicritère, phonétique et porter sur les données courantes et historisées.</p> <p></p> <p>Les services actuellement disponibles interrogent :</p> <ul> <li> les unités légales (siren) </li> <li> les établissements (siret). </li> </ul> <p>Le service informations permet de connaître les dates de dernières mises à jour.</p> <p>Le service Liens de succession informe sur les prédécesseurs et les successeurs des établissements.</p> <p align=\"justify\" style=\"margin-top: 0.6cm\">Le service nonDiffusibles restitue les siren et siret des personnes physiques ayant demandé à être exclues de la diffusion publique conformément à l'article A123-96 du code de commerce. Les informations les concernant ne peuvent alors être rediffusées, ni utilisées à des fins de prospection. Les utilisateurs ayant un référentiel en interne peuvent ainsi le mettre à jour quotidiennement.</p> <p>La lettre <b>Sirene open data actualités</b> est destinée aux utilisateurs des données Sirene. Pour vous abonner, <a href=\"https://insee.fr/fr/information/1405555\">suivez ce lien</a>. Pour consulter les précédents numéros, <a href=\"https://insee.fr/fr/information/3711739\">cliquez ici</a>.</p>
 *
 * The version of the OpenAPI document: 3.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SireneApi.Client.OpenAPIDateConverter;

namespace SireneApi.Model
{
    /// <summary>
    /// Objet représentant un comptage particulier à l&#39;intérieur d&#39;une facette
    /// </summary>
    [DataContract(Name = "Comptage")]
    public partial class Comptage : IEquatable<Comptage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Comptage" /> class.
        /// </summary>
        /// <param name="valeur">Modalité comptée.</param>
        /// <param name="nombre">Nombre d&#39;éléments correspondant à la modalité comptée.</param>
        /// <param name="facettes">facettes.</param>
        public Comptage(Object valeur = default(Object), long nombre = default(long), List<Facette> facettes = default(List<Facette>))
        {
            this.Valeur = valeur;
            this.Nombre = nombre;
            this.Facettes = facettes;
        }

        /// <summary>
        /// Modalité comptée
        /// </summary>
        /// <value>Modalité comptée</value>
        [DataMember(Name = "valeur", EmitDefaultValue = false)]
        public Object Valeur { get; set; }

        /// <summary>
        /// Nombre d&#39;éléments correspondant à la modalité comptée
        /// </summary>
        /// <value>Nombre d&#39;éléments correspondant à la modalité comptée</value>
        [DataMember(Name = "nombre", EmitDefaultValue = false)]
        public long Nombre { get; set; }

        /// <summary>
        /// Gets or Sets Facettes
        /// </summary>
        [DataMember(Name = "facettes", EmitDefaultValue = false)]
        public List<Facette> Facettes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Comptage {\n");
            sb.Append("  Valeur: ").Append(Valeur).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Facettes: ").Append(Facettes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Comptage);
        }

        /// <summary>
        /// Returns true if Comptage instances are equal
        /// </summary>
        /// <param name="input">Instance of Comptage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Comptage input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Valeur == input.Valeur ||
                    (this.Valeur != null &&
                    this.Valeur.Equals(input.Valeur))
                ) && 
                (
                    this.Nombre == input.Nombre ||
                    this.Nombre.Equals(input.Nombre)
                ) && 
                (
                    this.Facettes == input.Facettes ||
                    this.Facettes != null &&
                    input.Facettes != null &&
                    this.Facettes.SequenceEqual(input.Facettes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Valeur != null)
                {
                    hashCode = (hashCode * 59) + this.Valeur.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Nombre.GetHashCode();
                if (this.Facettes != null)
                {
                    hashCode = (hashCode * 59) + this.Facettes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
