---

- name: Create traefik network
  community.docker.docker_network:
    name: "{{ traefik_network }}"

- name: Include secret role
  include_role:
    name: secret
  vars:
    env_file : "{{ traefik_env_file }}"
    deploy_location : "{{ traefik_deploy_location }}"

- name: Include deploy role
  include_role:
    name: deploy
  vars:
    compose_file: "{{ traefik_compose_file }}"
    deploy_location : "{{ traefik_deploy_location }}"