/* tslint:disable */
/* eslint-disable */
/**
 * API Artisashop
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GPSCoord } from './GPSCoord';
import {
    GPSCoordFromJSON,
    GPSCoordFromJSONTyped,
    GPSCoordToJSON,
} from './GPSCoord';

/**
 * 
 * @export
 * @interface BoundInfo
 */
export interface BoundInfo {
    /**
     * 
     * @type {GPSCoord}
     * @memberof BoundInfo
     */
    northeast?: GPSCoord;
    /**
     * 
     * @type {GPSCoord}
     * @memberof BoundInfo
     */
    southwest?: GPSCoord;
}

/**
 * Check if a given object implements the BoundInfo interface.
 */
export function instanceOfBoundInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BoundInfoFromJSON(json: any): BoundInfo {
    return BoundInfoFromJSONTyped(json, false);
}

export function BoundInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoundInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'northeast': !exists(json, 'northeast') ? undefined : GPSCoordFromJSON(json['northeast']),
        'southwest': !exists(json, 'southwest') ? undefined : GPSCoordFromJSON(json['southwest']),
    };
}

export function BoundInfoToJSON(value?: BoundInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'northeast': GPSCoordToJSON(value.northeast),
        'southwest': GPSCoordToJSON(value.southwest),
    };
}

