/* tslint:disable */
/* eslint-disable */
/**
 * API Artisashop
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialInfo
 */
export interface SocialInfo {
    /**
     * 
     * @type {string}
     * @memberof SocialInfo
     */
    blog?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SocialInfo
     */
    twitter?: string | null;
}

/**
 * Check if a given object implements the SocialInfo interface.
 */
export function instanceOfSocialInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SocialInfoFromJSON(json: any): SocialInfo {
    return SocialInfoFromJSONTyped(json, false);
}

export function SocialInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog': !exists(json, 'blog') ? undefined : json['blog'],
        'twitter': !exists(json, 'twitter') ? undefined : json['twitter'],
    };
}

export function SocialInfoToJSON(value?: SocialInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog': value.blog,
        'twitter': value.twitter,
    };
}

