/* tslint:disable */
/* eslint-disable */
/**
 * API Artisashop
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductStyle,
} from '../models';
import {
    ProductStyleFromJSON,
    ProductStyleToJSON,
} from '../models';

export interface AdminProductStyleAdminProductStyleGetRequest {
    filter?: string;
    range?: string;
    sort?: string;
}

export interface AdminProductStyleAdminProductStyleIdDeleteRequest {
    id: number;
}

export interface AdminProductStyleAdminProductStyleIdGetRequest {
    id: number;
}

export interface AdminProductStyleAdminProductStyleIdPutRequest {
    id: number;
    productStyle?: ProductStyle;
}

export interface AdminProductStyleAdminProductStylePostRequest {
    productStyle?: ProductStyle;
}

/**
 * 
 */
export class AdminProductStyleApi extends runtime.BaseAPI {

    /**
     */
    async adminProductStyleAdminProductStyleGetRaw(requestParameters: AdminProductStyleAdminProductStyleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductStyle>>> {
        const queryParameters: any = {};

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        if (requestParameters.range !== undefined) {
            queryParameters['range'] = requestParameters.range;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters['sort'] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/admin/productStyle/AdminProductStyle`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductStyleFromJSON));
    }

    /**
     */
    async adminProductStyleAdminProductStyleGet(requestParameters: AdminProductStyleAdminProductStyleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductStyle>> {
        const response = await this.adminProductStyleAdminProductStyleGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async adminProductStyleAdminProductStyleIdDeleteRaw(requestParameters: AdminProductStyleAdminProductStyleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductStyle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling adminProductStyleAdminProductStyleIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/admin/productStyle/AdminProductStyle/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductStyleFromJSON(jsonValue));
    }

    /**
     */
    async adminProductStyleAdminProductStyleIdDelete(requestParameters: AdminProductStyleAdminProductStyleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductStyle> {
        const response = await this.adminProductStyleAdminProductStyleIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async adminProductStyleAdminProductStyleIdGetRaw(requestParameters: AdminProductStyleAdminProductStyleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductStyle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling adminProductStyleAdminProductStyleIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/admin/productStyle/AdminProductStyle/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductStyleFromJSON(jsonValue));
    }

    /**
     */
    async adminProductStyleAdminProductStyleIdGet(requestParameters: AdminProductStyleAdminProductStyleIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductStyle> {
        const response = await this.adminProductStyleAdminProductStyleIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async adminProductStyleAdminProductStyleIdPutRaw(requestParameters: AdminProductStyleAdminProductStyleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductStyle>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling adminProductStyleAdminProductStyleIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/admin/productStyle/AdminProductStyle/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProductStyleToJSON(requestParameters.productStyle),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductStyleFromJSON(jsonValue));
    }

    /**
     */
    async adminProductStyleAdminProductStyleIdPut(requestParameters: AdminProductStyleAdminProductStyleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductStyle> {
        const response = await this.adminProductStyleAdminProductStyleIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async adminProductStyleAdminProductStylePostRaw(requestParameters: AdminProductStyleAdminProductStylePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductStyle>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/admin/productStyle/AdminProductStyle`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductStyleToJSON(requestParameters.productStyle),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductStyleFromJSON(jsonValue));
    }

    /**
     */
    async adminProductStyleAdminProductStylePost(requestParameters: AdminProductStyleAdminProductStylePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductStyle> {
        const response = await this.adminProductStyleAdminProductStylePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
