---
- name: Make sure .secret folder exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.secret/"
    state: directory
    mode: '0755'
- name: Make sure {{ deploy_location }} folder exists
  ansible.builtin.file:
    path: "{{ deploy_location }}"
    state: directory
    mode: '0755'
- name: Copy .env file to host
  copy:
    src: "{{ env_file }}"
    dest: "/home/{{ ansible_user }}/.secret/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0655
- name: Copy deployement key to distant location
  copy:
    src: "{{ deploy_key }}"
    dest: "/home/{{ ansible_user }}/.secret/deploy_key"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  when: deploy_key is defined