/* tslint:disable */
/* eslint-disable */
/**
 * API Artisashop
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Amount } from './Amount';
import {
    AmountFromJSON,
    AmountFromJSONTyped,
    AmountToJSON,
} from './Amount';
import type { ItemElem } from './ItemElem';
import {
    ItemElemFromJSON,
    ItemElemFromJSONTyped,
    ItemElemToJSON,
} from './ItemElem';

/**
 * 
 * @export
 * @interface PurchaseUnitElem
 */
export interface PurchaseUnitElem {
    /**
     * 
     * @type {Amount}
     * @memberof PurchaseUnitElem
     */
    amount: Amount;
    /**
     * 
     * @type {Array<ItemElem>}
     * @memberof PurchaseUnitElem
     */
    items: Array<ItemElem>;
}

/**
 * Check if a given object implements the PurchaseUnitElem interface.
 */
export function instanceOfPurchaseUnitElem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function PurchaseUnitElemFromJSON(json: any): PurchaseUnitElem {
    return PurchaseUnitElemFromJSONTyped(json, false);
}

export function PurchaseUnitElemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseUnitElem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': AmountFromJSON(json['amount']),
        'items': ((json['items'] as Array<any>).map(ItemElemFromJSON)),
    };
}

export function PurchaseUnitElemToJSON(value?: PurchaseUnitElem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': AmountToJSON(value.amount),
        'items': ((value.items as Array<any>).map(ItemElemToJSON)),
    };
}

