/* tslint:disable */
/* eslint-disable */
/**
 * API Artichaut
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSearch
 */
export interface ProductSearch {
    /**
     * 
     * @type {string}
     * @memberof ProductSearch
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSearch
     */
    job?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductSearch
     */
    styles?: Array<string> | null;
}

/**
 * Check if a given object implements the ProductSearch interface.
 */
export function instanceOfProductSearch(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductSearchFromJSON(json: any): ProductSearch {
    return ProductSearchFromJSONTyped(json, false);
}

export function ProductSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSearch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'job': !exists(json, 'job') ? undefined : json['job'],
        'styles': !exists(json, 'styles') ? undefined : json['styles'],
    };
}

export function ProductSearchToJSON(value?: ProductSearch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'job': value.job,
        'styles': value.styles,
    };
}

