/*
 * API Artisashop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ArtisashopApi.Client;
using ArtisashopApi.Api;
// uncomment below to import models
//using ArtisashopApi.Model;

namespace ArtisashopApi.Test.Api
{
    /// <summary>
    ///  Class for testing AdminUserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdminUserApiTests : IDisposable
    {
        private AdminUserApi instance;

        public AdminUserApiTests()
        {
            instance = new AdminUserApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminUserApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AdminUserApi
            //Assert.IsType<AdminUserApi>(instance);
        }

        /// <summary>
        /// Test ApiAdminUserGet
        /// </summary>
        [Fact]
        public void ApiAdminUserGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? filter = null;
            //string? range = null;
            //string? sort = null;
            //var response = instance.ApiAdminUserGet(filter, range, sort);
            //Assert.IsType<List<Account>>(response);
        }

        /// <summary>
        /// Test ApiAdminUserIdDelete
        /// </summary>
        [Fact]
        public void ApiAdminUserIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ApiAdminUserIdDelete(id);
            //Assert.IsType<Account>(response);
        }

        /// <summary>
        /// Test ApiAdminUserIdGet
        /// </summary>
        [Fact]
        public void ApiAdminUserIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ApiAdminUserIdGet(id);
            //Assert.IsType<Account>(response);
        }

        /// <summary>
        /// Test ApiAdminUserIdPut
        /// </summary>
        [Fact]
        public void ApiAdminUserIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //Account? account = null;
            //var response = instance.ApiAdminUserIdPut(id, account);
            //Assert.IsType<Account>(response);
        }

        /// <summary>
        /// Test ApiAdminUserPost
        /// </summary>
        [Fact]
        public void ApiAdminUserPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Account? account = null;
            //var response = instance.ApiAdminUserPost(account);
            //Assert.IsType<Account>(response);
        }
    }
}
