/*
 * API Artisashop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ArtisashopApi.Client;
using ArtisashopApi.Api;
// uncomment below to import models
//using ArtisashopApi.Model;

namespace ArtisashopApi.Test.Api
{
    /// <summary>
    ///  Class for testing BasketApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BasketApiTests : IDisposable
    {
        private BasketApi instance;

        public BasketApiTests()
        {
            instance = new BasketApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BasketApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BasketApi
            //Assert.IsType<BasketApi>(instance);
        }

        /// <summary>
        /// Test ApiBasketBasketIdDelete
        /// </summary>
        [Fact]
        public void ApiBasketBasketIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int basketId = null;
            //var response = instance.ApiBasketBasketIdDelete(basketId);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiBasketGet
        /// </summary>
        [Fact]
        public void ApiBasketGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiBasketGet();
            //Assert.IsType<List<Basket>>(response);
        }

        /// <summary>
        /// Test ApiBasketPatch
        /// </summary>
        [Fact]
        public void ApiBasketPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateBasket? updateBasket = null;
            //var response = instance.ApiBasketPatch(updateBasket);
            //Assert.IsType<Basket>(response);
        }

        /// <summary>
        /// Test ApiBasketPayGet
        /// </summary>
        [Fact]
        public void ApiBasketPayGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? body = null;
            //var response = instance.ApiBasketPayGet(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ApiBasketPost
        /// </summary>
        [Fact]
        public void ApiBasketPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateBasket? createBasket = null;
            //var response = instance.ApiBasketPost(createBasket);
            //Assert.IsType<Basket>(response);
        }
    }
}
