/*
 * API Artisashop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ArtisashopApi.Client;
using ArtisashopApi.Api;

namespace ArtisashopApi.Test.Api
{
    /// <summary>
    ///  Class for testing OidcConfigurationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OidcConfigurationApiTests : IDisposable
    {
        private OidcConfigurationApi instance;

        public OidcConfigurationApiTests()
        {
            instance = new OidcConfigurationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OidcConfigurationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OidcConfigurationApi
            //Assert.IsType<OidcConfigurationApi>(instance);
        }

        /// <summary>
        /// Test ConfigurationClientIdGet
        /// </summary>
        [Fact]
        public void ConfigurationClientIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string clientId = null;
            //instance.ConfigurationClientIdGet(clientId);
        }
    }
}
