all:
  hosts:
    artisashop.fr
  children:
    instances:
      hosts:
        main:
          ansible_host: artisashop.fr
          ansible_port: 22
    azure:
      hosts:
        127.0.0.1
