version: '3.8'
services:
  backend:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - PARSE_ARTISASHOP_MASTER_KEY=${PARSE_ARTISASHOP_MASTER_KEY}
      - PARSE_ARTISASHOP_RESTAPI_KEY=${PARSE_ARTISASHOP_RESTAPI_KEY}
    build:
      context: ./Backend
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    networks:
      - traefik-tier
      - db-tier
      - mail-tier
    labels:
      - "traefik.enable=true"
      # - "traefik.http.${COMPOSE_PROJECT_NAME}-artisaback.rule=Host(`api.${ARTISASHOP_HOST}`)"
      # - "traefik.http.${COMPOSE_PROJECT_NAME}-artisaback.entrypoints=websecure"
      # - "traefik.http.${COMPOSE_PROJECT_NAME}-artisaback.priority=820"
      # - "traefik.http.services.${COMPOSE_PROJECT_NAME}-backend.loadbalancer.server.port=80"

      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend.rule=Host(`api.${ARTISASHOP_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-backend.entrypoints=websecure"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-backend.loadbalancer.server.port=80"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisafront.rule=Host(`${ARTISASHOP_HOST}`)"
      # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisafront.entrypoints=websecure"
      # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-artisafront.middlewares=${COMPOSE_PROJECT_NAME}-redirect-shop"
      # - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-shop.redirectregex.regex=(http(s*)://)?${ARTISASHOP_HOST}/?(.*)"
      # - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-shop.redirectregex.replacement=https://${ARTISASHOP_HOST}/$${3}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-frontend.rule=Host(`${ARTISASHOP_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-frontend.entrypoints=websecure"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-frontend.loadbalancer.server.port=80"
    networks:
      - traefik-tier

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dbsrcipts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    networks:
      - traefik-tier
      - db-tier
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

# db:
#   image: mysql
#   command: --default-authentication-plugin=mysql_native_password
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: 'R291Z25hZmllcg=='
#     MYSQL_DATABASE: 'store_db'
#     MYSQL_USER: 'store_user'
#     MYSQL_PASSWORD: 'store_user'
#   expose:
#     - '3306'
#   networks:
#     - traefik-tier
#     - db-tier
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

# smtp-server:
#   image: namshi/smtp:latest
#   restart: unless-stopped
#   networks:
#     - mail-tier
#   environment:
#     - SMARTHOST_USER=artisashop
#     - SMARTHOST_PASSWORD=artisashop2021=)
#   ports:
#     - 25:25

volumes:
  db-data:

networks:
  db-tier:
    driver: bridge
  mail-tier:
    driver: bridge
  traefik-tier:
    external:
      name: ${TRAEFIK_DOCKER_NETWORK}